services:

  mysql:
    image: mysql:8
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: Vinod789
      MYSQL_DATABASE: employee_db

  student-app:
    build: .
    container_name: student-app

    ports:
      - "8081:8081"

    depends_on:
      - mysql